spring.application.name=RestApi-Practice

# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/registration_db

# Database username
spring.datasource.username=root

# Database password
spring.datasource.password=test

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

